*** Variables ***

# Login page locators

${userNameInputField}   id:user-name
${passwordInputField}   id:password
${loginBtn}             id:login-button

#  Country selection page locators

${countrySelectionDropDown}     //*[@class='android.widget.Spinner']
${countryList}      //android.widget.ListView/android.widget.TextView
${selectCountry}       //android.widget.TextView[@text='Brazil']
${letsShpBtn}       class=android.widget.Button





